### ISSUE TITLE
Crash with Dynamic/Dramatic Trees.

### ISSUE THREAD

**Issue by MagmaBro123** [fonnymunkey/FermiumASM#10]
I hope I'm not just wasting my time and talking to an endless void (and I hope 3rd time's the charm), since 2 other users have also reported this on the original CensoredASM page (https://github.com/LoliKingdom/LoliASM/issues/141 and https://github.com/LoliKingdom/LoliASM/issues/17) and both have been open for months with no proper fix since then.

https://pastebin.com/GmL7skwZ

Modlist in report. (Giving this anyway but I really shouldn't have to since both mods are all over the report.)

**Comment by fonnymunkey** [comment]
Workaround added in 5.22
If you did not already apply the manual fix mentioned in the linked issue threads, wipe your "classesThatCallBakedQuadCtor" in the config to allow it to regenerate.

**Comment by MagmaBro123** [comment]
It seems this and Dynamic Trees still produces a crash every so often on startup, though its pretty rare.

[crash-2024-05-03_12.00.11-client.txt](https://github.com/fonnymunkey/FermiumASM/files/15203481/crash-2024-05-03_12.00.11-client.txt)

**Comment by fonnymunkey** [comment]
That crash is a separate issue, and seems to be an incompatibility between DynamicTrees and the option releaseSpriteFramesCache.
For now, disabling releaseSpriteFramesCache in the config should resolve it.

**Comment by MagmaBro123** [comment]
Ah. Hope a fix comes next release.

**Comment by MagmaBro123** [comment]
> That crash is a separate issue, and seems to be an incompatibility between DynamicTrees and the option releaseSpriteFramesCache. For now, disabling releaseSpriteFramesCache in the config should resolve it.

Still crashes. 

https://pastebin.com/GzjXJd85

**Comment by fonnymunkey** [comment]
None of that code runs if that config option is disabled, if you disabled it while ingame you will need to restart the game for it to take effect.
The only other way for that crash to still be happening would be if a different mod was somehow forcing it to take effect, or if the option was disabled in a different config such as censoredasm.cfg and not in normalasm.cfg.

**Comment by MagmaBro123** [comment]
> None of that code runs if that config option is disabled, if you disabled it while ingame you will need to restart the game for it to take effect. The only other way for that crash to still be happening would be if a different mod was somehow forcing it to take effect, or if the option was disabled in a different config such as censoredasm.cfg and not in normalasm.cfg.

I never touch in-game configs. I used the normalasm.cfg.

**Comment by fonnymunkey** [comment]
I just tested to be sure, the class FramesTextureData, which is part of the crash, is never even initialized if releaseSpriteFramesCache is disabled.
If releaseSpriteFramesCache is false in normalasm.cfg, the only way I can see that crash still happening is if; 
1. Another mod is manually utilizing FramesTextureData, which IMO is unlikely and I haven't seen any mods doing it, or
2. A mod is breaking the normalasm.cfg file loading/config file loading in general and causing releaseSpriteFramesCache to use the default value, or
3. You have a file system permission issue preventing normalasm.cfg from being read, causing it to use the default value.

I would recommend removing some mods such as MixinBooter or VintageFix and testing, and then also checking that the folder/files permissions of your install location are not protected in some way such as being a OneDrive directory.
