### ISSUE TITLE
crashed because of "Unknown"

### ISSUE THREAD

**Issue by Dreygonn** [fonnymunkey/FermiumASM#22]
Log: https://mclo.gs/kBCWmah
 i wanted to make a modpack to play with some friends :< (i also tried a couple diffrent ASMs to see if it was a problem with Fermium)
[crash-2024-10-03_19.09.54-client.txt](https://github.com/user-attachments/files/17247097/crash-2024-10-03_19.09.54-client.txt)
![wdym unknowm mc](https://github.com/user-attachments/assets/a165d50c-4669-47fd-a344-b658cee67fbb)

**Comment by fonnymunkey** [comment]
You have these errors in the log:
net.minecraftforge.fml.common.MissingModsException: Mod alfheim (Alfheim) requires [mixinbooter@[8.8,)]
net.minecraftforge.fml.common.MissingModsException: Mod packetfixer (Packet Fixer) requires [mixinbooter]
net.minecraftforge.fml.common.MissingModsException: Mod jeid (RoughlyEnoughIDs) requires [mixinbooter@[8.0,)]
net.minecraftforge.fml.common.MissingModsException: Mod universaltweaks (Universal Tweaks) requires [mixinbooter@[8.9,)]

As far as I've heard, Essential has compatibility issues with MixinBooter, as well as multiple other mods.
Try removing Essential and relaunching, and upload the new crash report if it crashes again.

The cause being "Unknown" just means FermiumASM couldn't determine a likely source, not that itself caused the crash.

**Comment by Dreygonn** [comment]
I no longer get that issue, now it seems to be an issue with forge
https://mclo.gs/vKLSg1u
![crash bc of forge](https://github.com/user-attachments/assets/441d6040-4ea5-4c00-89cc-217fefd6aafd)

**Comment by fonnymunkey** [comment]
The mod PacketFixer failed to apply its mixin which led to Forge being unable to load needed classes, as PacketFixer likely conflicts with UniversalTweaks and/or JEID as both of those modify the same class as PacketFixer.
I would recommend to try removing PacketFixer, as its fixes are likely already included in UniversalTweaks.

I recommend trying a discord with modpack development support such as Modded Minecraft Community for posting and getting help with these crash logs, FermiumASM is just improving and uploading these crash reports, not causing them/related to them.
