### ISSUE TITLE
onDemandAnimatedTextures stop texture animation when Optifine/Nothrium are installed

### ISSUE THREAD

**Issue by leonpano2006** [fonnymunkey/FermiumASM#5]
i confirm mod items have no animation when this mod is installed with optfine
similar to [this issue](https://github.com/LoliKingdom/LoliASM/issues/130) form loliasm but i didn't install Nothirium
please make fix for this

**Comment by fonnymunkey** [comment]
That issue is saying either, not both.
Turn off onDemandAnimatedTextures

**Comment by leonpano2006** [comment]
> That issue is saying either, not both. Turn off onDemandAnimatedTextures

i tried once
that will make my minecraft extreme lag

**Comment by fonnymunkey** [comment]
Many of the options in this mod are invasive changes and will be incompatible with certain mods, most will require disabling certain options the more mods you add.

If you're using Optifine or Nothrium, disable onDemandAnimatedTextures if you want animated textures.

There is an open PR for Nothrium to make changes to fix this but I do not expect it to be merged, and Optifine is unlikely to ever fix it, and I wouldn't expect them to anyways.

Turning off onDemandAnimatedTextures makes it have vanilla behavior, if it makes your performance worse then you have some other issue with your game going on.

**Comment by fonnymunkey** [comment]
Closing to merge issue into #12
