### ISSUE TITLE
Game crashes with Vintagium

### ISSUE THREAD

**Issue by NostalgicLorikeet** [fonnymunkey/FermiumASM#8]
Vintagium appears to have recently added compatibility with FASM, but the game still crashes with the two installed UNLESS `squashBakedQuads` is set to `false`. The config says that it is automatically disabled with Optifine installed so a solution could be to do the same with Vintagium.

**Comment by NostalgicLorikeet** [comment]
Opened a pull request to add a check for Vintagium, haven't check if it works though

**Comment by fonnymunkey** [comment]
Closed by #9
